/**
 * Every error this API can answer with, as a stable machine-readable code.
 *
 * The `message` on an error response is human copy: it is Vietnamese today, it may be
 * translated tomorrow, and its wording moves whenever somebody rewords a sentence. A client
 * that branches on it breaks the first time that happens - silently, and in production; the
 * dashboard has a `message.includes(...)` on a Vietnamese phrase in it today. `code` is the
 * half of the contract that does not move, so clients switch on this and render their own
 * text.
 *
 * **Every `HttpException` raised in this codebase carries one**, passed as the first key of
 * the object body - `AllExceptionsFilter` spreads the rest of that object through untouched,
 * so nothing else has to know about it:
 *
 *     new NotFoundException({ code: ErrorCode.ORDER_NOT_FOUND, message: 'Khong tim thay...' })
 *
 * Each value is its own key, so `ErrorCode.X` is a compile error for a code that is not
 * listed here - which is what keeps this file the complete list rather than a stale sample.
 *
 * Codes are **append-only**: renaming one is a breaking API change for every client that has
 * shipped a branch on it. Add a new code instead, and reuse an existing one wherever two call
 * sites are the same failure to whoever is reading it.
 */
export const ErrorCode = {
  // --- Access, identity and scope --------------------------------------------
  ACCOUNT_HAS_NO_BRANCH: 'ACCOUNT_HAS_NO_BRANCH',
  ACCOUNT_HAS_NO_LOCATION: 'ACCOUNT_HAS_NO_LOCATION',
  ACCOUNT_HAS_NO_TENANT: 'ACCOUNT_HAS_NO_TENANT',
  ADMIN_ONLY: 'ADMIN_ONLY',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SCOPE_FILTER_DENIED: 'SCOPE_FILTER_DENIED',
  TENANT_ID_REQUIRED: 'TENANT_ID_REQUIRED',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  TENANT_OWNER_ONLY: 'TENANT_OWNER_ONLY',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  // --- Generic request problems ----------------------------------------------
  BAD_REQUEST: 'BAD_REQUEST',
  BRANCH_ID_REQUIRED: 'BRANCH_ID_REQUIRED',
  DATE_RANGE_INVALID: 'DATE_RANGE_INVALID',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  QUANTITY_MUST_BE_POSITIVE: 'QUANTITY_MUST_BE_POSITIVE',
  REPORT_RANGE_TOO_LONG: 'REPORT_RANGE_TOO_LONG',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // --- Database constraints (translated from Prisma) -------------------------
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RELATION_VIOLATION: 'RELATION_VIOLATION',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  UNIQUE_VIOLATION: 'UNIQUE_VIOLATION',
  VALUE_TOO_LONG: 'VALUE_TOO_LONG',

  // --- Authentication and sessions -------------------------------------------
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_NOT_FOUND_OR_LOCKED: 'ACCOUNT_NOT_FOUND_OR_LOCKED',
  ACCOUNT_NOT_REGISTERED: 'ACCOUNT_NOT_REGISTERED',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  GOOGLE_EMAIL_MISSING: 'GOOGLE_EMAIL_MISSING',
  GOOGLE_EMAIL_UNVERIFIED: 'GOOGLE_EMAIL_UNVERIFIED',
  GOOGLE_SIGNIN_NOT_CONFIGURED: 'GOOGLE_SIGNIN_NOT_CONFIGURED',
  GOOGLE_TOKEN_INVALID: 'GOOGLE_TOKEN_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  LOGIN_MOBILE_STAFF_ONLY: 'LOGIN_MOBILE_STAFF_ONLY',
  LOGIN_WEB_CUSTOMER_DENIED: 'LOGIN_WEB_CUSTOMER_DENIED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',
  PASSWORD_CONFIRMATION_MISMATCH: 'PASSWORD_CONFIRMATION_MISMATCH',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_WRONG_TYPE: 'RESET_TOKEN_WRONG_TYPE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SMS_NOT_CONFIGURED: 'SMS_NOT_CONFIGURED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // --- Phone and citizen ID validation ---------------------------------------
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  IDENTIFICATION_ALREADY_IN_USE: 'IDENTIFICATION_ALREADY_IN_USE',
  IDENTIFICATION_DOB_INVALID: 'IDENTIFICATION_DOB_INVALID',
  IDENTIFICATION_GENDER_MISMATCH: 'IDENTIFICATION_GENDER_MISMATCH',
  IDENTIFICATION_LENGTH_INVALID: 'IDENTIFICATION_LENGTH_INVALID',
  IDENTIFICATION_NOT_NUMERIC: 'IDENTIFICATION_NOT_NUMERIC',
  IDENTIFICATION_PROVINCE_INVALID: 'IDENTIFICATION_PROVINCE_INVALID',
  IDENTIFICATION_REQUIRED: 'IDENTIFICATION_REQUIRED',
  IDENTIFICATION_YEAR_MISMATCH: 'IDENTIFICATION_YEAR_MISMATCH',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  PHONE_LENGTH_INVALID: 'PHONE_LENGTH_INVALID',
  PHONE_NOT_REGISTERED: 'PHONE_NOT_REGISTERED',
  PHONE_PREFIX_INVALID: 'PHONE_PREFIX_INVALID',
  PHONE_REQUIRED: 'PHONE_REQUIRED',
  PHONE_RESERVED_RANGE: 'PHONE_RESERVED_RANGE',

  // --- Tenants, plans and subscriptions --------------------------------------
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  PLAN_IS_FREE: 'PLAN_IS_FREE',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_QUOTA_EXCEEDED: 'PLAN_QUOTA_EXCEEDED',
  PLAN_UPDATE_EMPTY: 'PLAN_UPDATE_EMPTY',
  SUBSCRIPTION_ALREADY_EXISTS: 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_MISSING: 'SUBSCRIPTION_MISSING',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  TENANT_BANKING_NOT_CONFIGURED: 'TENANT_BANKING_NOT_CONFIGURED',
  TENANT_NAME_TAKEN: 'TENANT_NAME_TAKEN',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TRIAL_CANNOT_RENEW: 'TRIAL_CANNOT_RENEW',
  TRIAL_PLAN_UNAVAILABLE: 'TRIAL_PLAN_UNAVAILABLE',
  WEBHOOK_API_KEY_INVALID: 'WEBHOOK_API_KEY_INVALID',

  // --- Locations - branches and warehouses -----------------------------------
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_NOT_IN_TENANT: 'BRANCH_NOT_IN_TENANT',
  LOCATION_ALREADY_DELETED: 'LOCATION_ALREADY_DELETED',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  LOCATION_STAFF_NOT_ELIGIBLE: 'LOCATION_STAFF_NOT_ELIGIBLE',
  LOCATION_STAFF_POSTED_ELSEWHERE: 'LOCATION_STAFF_POSTED_ELSEWHERE',
  LOCATION_STAFF_STILL_ATTACHED: 'LOCATION_STAFF_STILL_ATTACHED',
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  WAREHOUSE_NOT_IN_TENANT: 'WAREHOUSE_NOT_IN_TENANT',

  // --- Staff accounts and roles ----------------------------------------------
  ROLE_BEYOND_GRANT: 'ROLE_BEYOND_GRANT',
  ROLE_IN_USE: 'ROLE_IN_USE',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NOT_IN_TENANT: 'ROLE_NOT_IN_TENANT',
  STAFF_ACCOUNT_ALREADY_DEACTIVATED: 'STAFF_ACCOUNT_ALREADY_DEACTIVATED',
  STAFF_ACCOUNT_EXISTS: 'STAFF_ACCOUNT_EXISTS',
  STAFF_ACCOUNT_NOT_ACTIVATED: 'STAFF_ACCOUNT_NOT_ACTIVATED',
  STAFF_ACCOUNT_ONLY: 'STAFF_ACCOUNT_ONLY',
  STAFF_IS_LOCATION_MANAGER: 'STAFF_IS_LOCATION_MANAGER',
  STAFF_NOT_AT_BRANCH: 'STAFF_NOT_AT_BRANCH',
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  STAFF_SELF_EDIT_DENIED: 'STAFF_SELF_EDIT_DENIED',
  STAFF_SINGLE_LOCATION_REQUIRED: 'STAFF_SINGLE_LOCATION_REQUIRED',

  // --- Catalogue - products, brands, categories, suppliers -------------------
  BRAND_IN_USE: 'BRAND_IN_USE',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_PARENT_CYCLE: 'CATEGORY_PARENT_CYCLE',
  CATEGORY_PARENT_NOT_FOUND: 'CATEGORY_PARENT_NOT_FOUND',
  CATEGORY_PARENT_SELF: 'CATEGORY_PARENT_SELF',
  PRODUCT_DISCONTINUED: 'PRODUCT_DISCONTINUED',
  PRODUCT_HAS_STOCK: 'PRODUCT_HAS_STOCK',
  PRODUCT_IN_STOCK_MOVEMENT: 'PRODUCT_IN_STOCK_MOVEMENT',
  PRODUCT_IN_UNPAID_ORDER: 'PRODUCT_IN_UNPAID_ORDER',
  PRODUCT_ITEM_AT_LOCATION: 'PRODUCT_ITEM_AT_LOCATION',
  PRODUCT_ITEM_HAS_TRANSACTIONS: 'PRODUCT_ITEM_HAS_TRANSACTIONS',
  PRODUCT_ITEM_IN_PROMOTION: 'PRODUCT_ITEM_IN_PROMOTION',
  PRODUCT_ITEM_NOT_FOUND: 'PRODUCT_ITEM_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  SKU_DUPLICATE_IN_REQUEST: 'SKU_DUPLICATE_IN_REQUEST',
  SKU_TAKEN: 'SKU_TAKEN',
  SUPPLIER_CREDIT_LIMIT_EXCEEDED: 'SUPPLIER_CREDIT_LIMIT_EXCEEDED',
  SUPPLIER_HAS_DEBT: 'SUPPLIER_HAS_DEBT',
  SUPPLIER_HAS_TRANSACTIONS: 'SUPPLIER_HAS_TRANSACTIONS',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  SUPPLIER_PAYMENT_EXCEEDS_DEBT: 'SUPPLIER_PAYMENT_EXCEEDS_DEBT',

  // --- Inventory -------------------------------------------------------------
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_ALREADY_AT_LOCATION: 'INVENTORY_ALREADY_AT_LOCATION',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INVENTORY_STILL_HAS_STOCK: 'INVENTORY_STILL_HAS_STOCK',
  // Order journey (2026-10-02): holding stock, lots and the damaged-goods location.
  /** @deprecated Stock reservations were dropped (2026-10-04); nothing raises this. Kept because codes are append-only. */
  INSUFFICIENT_AVAILABLE_STOCK: 'INSUFFICIENT_AVAILABLE_STOCK',
  /** The lots at a location do not add up to what is being drawn - Σ lot.remaining has drifted from `stock`. A data fault, never user error. */
  INVENTORY_LOT_SHORTAGE: 'INVENTORY_LOT_SHORTAGE',
  /** Shipping or releasing more than is locked for orders at that location (2026-10-04) - the order was never packed there, or its lock was already shipped or released. */
  INVENTORY_LOCK_MISMATCH: 'INVENTORY_LOCK_MISMATCH',
  /** A custom piece has no lot made for its order line at that location. */
  INVENTORY_CUSTOM_LOT_NOT_FOUND: 'INVENTORY_CUSTOM_LOT_NOT_FOUND',
  /** Stock cannot be held or sold from a damaged-goods location (`isSellable = false`). */
  LOCATION_NOT_SELLABLE: 'LOCATION_NOT_SELLABLE',
  /** `damagedLocationId` must be another non-sellable location of the same tenant. */
  LOCATION_DAMAGED_INVALID: 'LOCATION_DAMAGED_INVALID',
  /** The location has no damaged-goods location to send defective / damaged units to. */
  LOCATION_DAMAGED_REQUIRED: 'LOCATION_DAMAGED_REQUIRED',
  /** @deprecated Stock reservations were dropped (2026-10-04); nothing raises this. Kept because codes are append-only. */
  RESERVATION_NOT_ACTIVE: 'RESERVATION_NOT_ACTIVE',
  /** @deprecated Stock reservations were dropped (2026-10-04); nothing raises this. Kept because codes are append-only. */
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',

  // --- Stock movements -------------------------------------------------------
  IMPORT_PRICE_ABOVE_RETAIL: 'IMPORT_PRICE_ABOVE_RETAIL',
  IMPORT_PRICE_MUST_BE_POSITIVE: 'IMPORT_PRICE_MUST_BE_POSITIVE',
  STOCK_MOVEMENT_ADJUST_HAS_DESTINATION:
    'STOCK_MOVEMENT_ADJUST_HAS_DESTINATION',
  STOCK_MOVEMENT_ADJUST_NEGATIVE: 'STOCK_MOVEMENT_ADJUST_NEGATIVE',
  STOCK_MOVEMENT_CANCEL_DENIED: 'STOCK_MOVEMENT_CANCEL_DENIED',
  STOCK_MOVEMENT_CANCEL_STATUS_INVALID: 'STOCK_MOVEMENT_CANCEL_STATUS_INVALID',
  STOCK_MOVEMENT_COUNTED_QTY_REQUIRED: 'STOCK_MOVEMENT_COUNTED_QTY_REQUIRED',
  STOCK_MOVEMENT_DESTINATION_REQUIRED: 'STOCK_MOVEMENT_DESTINATION_REQUIRED',
  STOCK_MOVEMENT_DUPLICATE_ITEM: 'STOCK_MOVEMENT_DUPLICATE_ITEM',
  STOCK_MOVEMENT_EMPTY: 'STOCK_MOVEMENT_EMPTY',
  STOCK_MOVEMENT_LOCATION_DENIED: 'STOCK_MOVEMENT_LOCATION_DENIED',
  STOCK_MOVEMENT_NOT_ADJUST: 'STOCK_MOVEMENT_NOT_ADJUST',
  STOCK_MOVEMENT_NOT_FOUND: 'STOCK_MOVEMENT_NOT_FOUND',
  STOCK_MOVEMENT_NO_ADJUSTMENT: 'STOCK_MOVEMENT_NO_ADJUSTMENT',
  STOCK_MOVEMENT_READ_DENIED: 'STOCK_MOVEMENT_READ_DENIED',
  STOCK_MOVEMENT_RECEIVED_QTY_EXCEEDS: 'STOCK_MOVEMENT_RECEIVED_QTY_EXCEEDS',
  STOCK_MOVEMENT_RECEIVED_QTY_REQUIRED: 'STOCK_MOVEMENT_RECEIVED_QTY_REQUIRED',
  STOCK_MOVEMENT_RECEIVE_EMPTY: 'STOCK_MOVEMENT_RECEIVE_EMPTY',
  STOCK_MOVEMENT_SAME_LOCATION: 'STOCK_MOVEMENT_SAME_LOCATION',
  STOCK_MOVEMENT_SHOULD_BE_RETURN: 'STOCK_MOVEMENT_SHOULD_BE_RETURN',
  STOCK_MOVEMENT_SOURCE_REQUIRED: 'STOCK_MOVEMENT_SOURCE_REQUIRED',
  STOCK_MOVEMENT_STATUS_INVALID: 'STOCK_MOVEMENT_STATUS_INVALID',
  STOCK_MOVEMENT_SUPPLIER_REQUIRED: 'STOCK_MOVEMENT_SUPPLIER_REQUIRED',
  STOCK_MOVEMENT_WRITE_DENIED: 'STOCK_MOVEMENT_WRITE_DENIED',
  // Two import flows (2026-10-02): SUPPLIER buys finished goods, WORKSHOP receives made-to-order goods.
  IMPORT_SOURCE_REQUIRED: 'IMPORT_SOURCE_REQUIRED',
  /** The supplier's `type` does not feed this `importSource` (GOODS ↔ SUPPLIER, WORKSHOP ↔ WORKSHOP). */
  IMPORT_SOURCE_SUPPLIER_MISMATCH: 'IMPORT_SOURCE_SUPPLIER_MISMATCH',
  /** Every line of a WORKSHOP import must point at a production request line. */
  IMPORT_PRODUCTION_ITEM_REQUIRED: 'IMPORT_PRODUCTION_ITEM_REQUIRED',
  /** The production request line belongs to another workshop / SKU, or is not open. */
  IMPORT_PRODUCTION_ITEM_MISMATCH: 'IMPORT_PRODUCTION_ITEM_MISMATCH',
  /** More received than the production request line still expects. */
  IMPORT_PRODUCTION_QTY_EXCEEDS: 'IMPORT_PRODUCTION_QTY_EXCEEDS',
  STOCK_MOVEMENT_DEFECT_QTY_EXCEEDS: 'STOCK_MOVEMENT_DEFECT_QTY_EXCEEDS',

  // --- Selling - orders, customers, promotions -------------------------------
  CASH_FLOW_NOT_FOUND: 'CASH_FLOW_NOT_FOUND',
  CUSTOMER_CODE_TAKEN: 'CUSTOMER_CODE_TAKEN',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_TAKEN: 'CUSTOMER_PHONE_TAKEN',
  ORDER_BRANCH_DENIED: 'ORDER_BRANCH_DENIED',
  ORDER_CUSTOMER_PAY_TOO_LOW: 'ORDER_CUSTOMER_PAY_TOO_LOW',
  ORDER_DISCOUNT_CONFLICT: 'ORDER_DISCOUNT_CONFLICT',
  ORDER_DISCOUNT_VALUE_REQUIRED: 'ORDER_DISCOUNT_VALUE_REQUIRED',
  ORDER_LINE_DISCOUNT_EXCEEDS_TOTAL: 'ORDER_LINE_DISCOUNT_EXCEEDS_TOTAL',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_PENDING_SEPAY: 'ORDER_NOT_PENDING_SEPAY',
  ORDER_PAYMENT_CONFLICT: 'ORDER_PAYMENT_CONFLICT',
  ORDER_PROMOTION_ALLOCATION_MISMATCH: 'ORDER_PROMOTION_ALLOCATION_MISMATCH',
  ORDER_STATUS_CONFLICT: 'ORDER_STATUS_CONFLICT',
  ORDER_STATUS_TRANSITION_INVALID: 'ORDER_STATUS_TRANSITION_INVALID',
  ORDER_TRANSFER_AMOUNT_SHORT: 'ORDER_TRANSFER_AMOUNT_SHORT',
  PROMOTION_BRANCH_DENIED: 'PROMOTION_BRANCH_DENIED',
  PROMOTION_CUSTOMER_USAGE_EXHAUSTED: 'PROMOTION_CUSTOMER_USAGE_EXHAUSTED',
  PROMOTION_MAX_DISCOUNT_INVALID: 'PROMOTION_MAX_DISCOUNT_INVALID',
  PROMOTION_NOT_APPLICABLE: 'PROMOTION_NOT_APPLICABLE',
  PROMOTION_NOT_ELIGIBLE: 'PROMOTION_NOT_ELIGIBLE',
  PROMOTION_NOT_FOUND: 'PROMOTION_NOT_FOUND',
  PROMOTION_NOT_STACKABLE: 'PROMOTION_NOT_STACKABLE',
  PROMOTION_ORDER_ID_REQUIRED: 'PROMOTION_ORDER_ID_REQUIRED',
  PROMOTION_STACK_LIMIT: 'PROMOTION_STACK_LIMIT',
  PROMOTION_USAGE_EXHAUSTED: 'PROMOTION_USAGE_EXHAUSTED',

  // --- Order journey (2026-10-02, docs/order-flow.md) -------------------------
  /** Every order past DRAFT / PENDING_CONFIRMATION needs a person in charge. */
  ORDER_ASSIGNEE_REQUIRED: 'ORDER_ASSIGNEE_REQUIRED',
  /** The assignee is not an active account of this tenant. */
  ORDER_ASSIGNEE_INVALID: 'ORDER_ASSIGNEE_INVALID',
  /** Packed and handed over - an OrderReturn is the only way back. */
  ORDER_CANCEL_NOT_ALLOWED: 'ORDER_CANCEL_NOT_ALLOWED',
  ORDER_COMBO_INVALID: 'ORDER_COMBO_INVALID',
  ORDER_EMPTY: 'ORDER_EMPTY',
  ORDER_ITEM_CUSTOM_LOCKED: 'ORDER_ITEM_CUSTOM_LOCKED',
  ORDER_ITEM_NOT_CUSTOMIZABLE: 'ORDER_ITEM_NOT_CUSTOMIZABLE',
  ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
  /** Only DRAFT / PENDING_CONFIRMATION orders can be confirmed. */
  ORDER_NOT_CONFIRMABLE: 'ORDER_NOT_CONFIRMABLE',
  /** Only a DRAFT may be edited freely. */
  ORDER_NOT_DRAFT: 'ORDER_NOT_DRAFT',
  ORDER_SOURCE_LOCATION_INVALID: 'ORDER_SOURCE_LOCATION_INVALID',

  // --- Workshop: production requests ----------------------------------------
  /** A custom SKU's line must point at the order line it is made for. */
  PRODUCTION_REQUEST_CUSTOM_LINE_REQUIRED:
    'PRODUCTION_REQUEST_CUSTOM_LINE_REQUIRED',
  PRODUCTION_REQUEST_EMPTY: 'PRODUCTION_REQUEST_EMPTY',
  PRODUCTION_REQUEST_ITEM_NOT_FOUND: 'PRODUCTION_REQUEST_ITEM_NOT_FOUND',
  /** Lines and specs are frozen once the request is SENT. */
  PRODUCTION_REQUEST_LOCKED: 'PRODUCTION_REQUEST_LOCKED',
  PRODUCTION_REQUEST_NOT_FOUND: 'PRODUCTION_REQUEST_NOT_FOUND',
  PRODUCTION_REQUEST_STATUS_INVALID: 'PRODUCTION_REQUEST_STATUS_INVALID',
  /** The supplier on a production request must be a WORKSHOP. */
  SUPPLIER_NOT_WORKSHOP: 'SUPPLIER_NOT_WORKSHOP',

  // --- Fulfillment & delivery -----------------------------------------------
  FULFILLMENT_ALREADY_EXISTS: 'FULFILLMENT_ALREADY_EXISTS',
  /** No longer raised: packing now answers ORDER_STEP_DENIED, the one refusal every journey step shares. Kept because codes are append-only. */
  FULFILLMENT_LOCATION_DENIED: 'FULFILLMENT_LOCATION_DENIED',
  FULFILLMENT_NOT_FOUND: 'FULFILLMENT_NOT_FOUND',
  /** No longer raised: split into FULFILLMENT_MULTIPLE_SOURCES / _LINE_NO_SOURCE / _NOTHING_TO_PACK, so the client can say what to do. Kept because codes are append-only. */
  FULFILLMENT_ORDER_NOT_READY: 'FULFILLMENT_ORDER_NOT_READY',
  /** The order's lines ship from more than one location - transfer the goods to one place before packing. */
  FULFILLMENT_MULTIPLE_SOURCES: 'FULFILLMENT_MULTIPLE_SOURCES',
  /** A line to be packed has no location to ship from. */
  FULFILLMENT_LINE_NO_SOURCE: 'FULFILLMENT_LINE_NO_SOURCE',
  /** Nothing on the order holds stock (only combo parents / services), so there is nothing to pack. */
  FULFILLMENT_NOTHING_TO_PACK: 'FULFILLMENT_NOTHING_TO_PACK',
  /** A multi-package item is missing packages. */
  FULFILLMENT_PACKAGES_INCOMPLETE: 'FULFILLMENT_PACKAGES_INCOMPLETE',
  FULFILLMENT_QTY_EXCEEDS: 'FULFILLMENT_QTY_EXCEEDS',
  FULFILLMENT_STATUS_INVALID: 'FULFILLMENT_STATUS_INVALID',
  /** Only the order's person in charge (or someone holding the permission) may verify the packed goods. */
  FULFILLMENT_VERIFY_DENIED: 'FULFILLMENT_VERIFY_DENIED',
  CARRIER_WEBHOOK_INVALID: 'CARRIER_WEBHOOK_INVALID',
  /** The fulfillment has not been handed over yet. */
  SHIPMENT_FULFILLMENT_NOT_HANDED_OVER: 'SHIPMENT_FULFILLMENT_NOT_HANDED_OVER',
  /** The shipper is not the driver on this shipment. */
  SHIPMENT_NOT_ASSIGNED: 'SHIPMENT_NOT_ASSIGNED',
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  /** An INTERNAL delivery needs at least one proof photo. */
  SHIPMENT_PROOF_REQUIRED: 'SHIPMENT_PROOF_REQUIRED',
  SHIPMENT_STATUS_INVALID: 'SHIPMENT_STATUS_INVALID',
  SHIPMENT_TRACKING_TAKEN: 'SHIPMENT_TRACKING_TAKEN',

  // --- Returns --------------------------------------------------------------
  ORDER_RETURN_CONDITION_REQUIRED: 'ORDER_RETURN_CONDITION_REQUIRED',
  /** Neither the order's person in charge nor a holder of `returns:create`. */
  ORDER_RETURN_DENIED: 'ORDER_RETURN_DENIED',
  ORDER_RETURN_EMPTY: 'ORDER_RETURN_EMPTY',
  ORDER_RETURN_NOT_FOUND: 'ORDER_RETURN_NOT_FOUND',
  /** Nothing has left the shop yet - cancel the order instead. */
  ORDER_RETURN_ORDER_NOT_RETURNABLE: 'ORDER_RETURN_ORDER_NOT_RETURNABLE',
  /** More than was sold minus what already came back. */
  ORDER_RETURN_QTY_EXCEEDS: 'ORDER_RETURN_QTY_EXCEEDS',
  ORDER_RETURN_STATUS_INVALID: 'ORDER_RETURN_STATUS_INVALID',

  // --- Marketplace channels & payments (Phase 2) ----------------------------
  CHANNEL_MAPPING_DUPLICATE: 'CHANNEL_MAPPING_DUPLICATE',
  CHANNEL_MAPPING_NOT_FOUND: 'CHANNEL_MAPPING_NOT_FOUND',
  PAYMENT_AMOUNT_EXCEEDS_DUE: 'PAYMENT_AMOUNT_EXCEEDS_DUE',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_REFUND_EXCEEDS_PAID: 'PAYMENT_REFUND_EXCEEDS_PAID',
  PAYMENT_STATUS_INVALID: 'PAYMENT_STATUS_INVALID',
  SALES_CHANNEL_ALREADY_CONNECTED: 'SALES_CHANNEL_ALREADY_CONNECTED',
  SALES_CHANNEL_AUTH_FAILED: 'SALES_CHANNEL_AUTH_FAILED',
  SALES_CHANNEL_NOT_CONFIGURED: 'SALES_CHANNEL_NOT_CONFIGURED',
  SALES_CHANNEL_NOT_FOUND: 'SALES_CHANNEL_NOT_FOUND',

  // --- Cash drawer sessions --------------------------------------------------
  CASH_DRAWER_ALREADY_OPEN: 'CASH_DRAWER_ALREADY_OPEN',
  CASH_DRAWER_BRANCH_DENIED: 'CASH_DRAWER_BRANCH_DENIED',
  CASH_DRAWER_CLOSED: 'CASH_DRAWER_CLOSED',
  CASH_DRAWER_CONFLICT: 'CASH_DRAWER_CONFLICT',
  CASH_DRAWER_END_LOG_REQUIRED: 'CASH_DRAWER_END_LOG_REQUIRED',
  CASH_DRAWER_NONE_OPEN: 'CASH_DRAWER_NONE_OPEN',
  CASH_DRAWER_NOT_FOUND: 'CASH_DRAWER_NOT_FOUND',
  CASH_DRAWER_NOT_HOLDER: 'CASH_DRAWER_NOT_HOLDER',
  SHIFT_LOG_HANDOVER_INVALID: 'SHIFT_LOG_HANDOVER_INVALID',
  SHIFT_LOG_NEXT_STAFF_INVALID: 'SHIFT_LOG_NEXT_STAFF_INVALID',
  SHIFT_LOG_NEXT_STAFF_SELF: 'SHIFT_LOG_NEXT_STAFF_SELF',
  SHIFT_LOG_START_REQUIRED: 'SHIFT_LOG_START_REQUIRED',

  // --- Scheduling and shift templates ----------------------------------------
  SCHEDULE_COMPLETED_CANNOT_DELETE: 'SCHEDULE_COMPLETED_CANNOT_DELETE',
  SCHEDULE_LOCATION_REQUIRED: 'SCHEDULE_LOCATION_REQUIRED',
  SCHEDULE_NOT_EDITABLE: 'SCHEDULE_NOT_EDITABLE',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEDULE_OVERLAP: 'SCHEDULE_OVERLAP',
  SCHEDULE_STAFF_INVALID: 'SCHEDULE_STAFF_INVALID',
  SCHEDULE_USER_NOT_ASSIGNED: 'SCHEDULE_USER_NOT_ASSIGNED',
  SHIFT_TEMPLATE_INVALID: 'SHIFT_TEMPLATE_INVALID',
  SHIFT_TEMPLATE_NOT_FOUND: 'SHIFT_TEMPLATE_NOT_FOUND',

  // --- Holidays --------------------------------------------------------------
  GOOGLE_CALENDAR_NOT_CONFIGURED: 'GOOGLE_CALENDAR_NOT_CONFIGURED',
  GOOGLE_CALENDAR_SYNC_FAILED: 'GOOGLE_CALENDAR_SYNC_FAILED',
  HOLIDAY_DATE_INVALID: 'HOLIDAY_DATE_INVALID',
  HOLIDAY_DUPLICATE: 'HOLIDAY_DUPLICATE',
  HOLIDAY_NOT_FOUND: 'HOLIDAY_NOT_FOUND',
  HOLIDAY_UPDATE_EMPTY: 'HOLIDAY_UPDATE_EMPTY',

  // --- Notifications, tickets, uploads and the AI assistant ------------------
  AI_CONVERSATION_NOT_FOUND: 'AI_CONVERSATION_NOT_FOUND',
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  STATS_LOCATION_DENIED: 'STATS_LOCATION_DENIED',
  TICKET_ACCESS_DENIED: 'TICKET_ACCESS_DENIED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_FILE_REQUIRED: 'UPLOAD_FILE_REQUIRED',
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_FORMAT_UNSUPPORTED: 'UPLOAD_FORMAT_UNSUPPORTED',
  UPLOAD_NOT_CONFIGURED: 'UPLOAD_NOT_CONFIGURED',

  // --- Order journey, revised 2026-10-04 (docs/api-contract-order-flow.md §6) ---
  ORDER_COLLECTION_AMOUNT_MISMATCH: 'ORDER_COLLECTION_AMOUNT_MISMATCH',
  ORDER_DEPOSIT_CHANGED: 'ORDER_DEPOSIT_CHANGED',
  ORDER_DEPOSIT_EXCEEDS_TOTAL: 'ORDER_DEPOSIT_EXCEEDS_TOTAL',
  ORDER_NOT_EDITABLE: 'ORDER_NOT_EDITABLE',
  ORDER_REMITTANCE_AMOUNT_MISMATCH: 'ORDER_REMITTANCE_AMOUNT_MISMATCH',
  ORDER_REMITTANCE_NOT_PENDING: 'ORDER_REMITTANCE_NOT_PENDING',
  ORDER_SHIP_INSUFFICIENT_STOCK: 'ORDER_SHIP_INSUFFICIENT_STOCK',
  IMPORT_WORKSHOP_VIA_PRODUCTION_REQUEST:
    'IMPORT_WORKSHOP_VIA_PRODUCTION_REQUEST',
  SHIPMENT_DRIVER_REQUIRED: 'SHIPMENT_DRIVER_REQUIRED',
  /** The named driver is not the shop owner, the order's person in charge, or an active staff member holding shipments:deliver. */
  SHIPMENT_DRIVER_INVALID: 'SHIPMENT_DRIVER_INVALID',
  /** An EXTERNAL (third-party carrier) shipment has no driver of ours. */
  SHIPMENT_DRIVER_NOT_ALLOWED: 'SHIPMENT_DRIVER_NOT_ALLOWED',
  /** A journey step (pack, hand over, change driver, ship) is open to the shop owner, the order's person in charge, or someone holding that step's permission at that location - and the caller is none of them. */
  ORDER_STEP_DENIED: 'ORDER_STEP_DENIED',
  SHIPMENT_ORDER_NOT_PACKED: 'SHIPMENT_ORDER_NOT_PACKED',
  SHIPMENT_ORDER_NOT_SHIPPING: 'SHIPMENT_ORDER_NOT_SHIPPING',
  /** Confirming a delivery is for our own shippers only; a third-party carrier's delivery is reported automatically (C-4, later). */
  SHIPMENT_DELIVER_INTERNAL_ONLY: 'SHIPMENT_DELIVER_INTERNAL_ONLY',
  /** "The customer paid cash instead" needs a QR balance still waiting for its transfer - there is none, or the money has just arrived. */
  ORDER_QR_PAYMENT_NOT_PENDING: 'ORDER_QR_PAYMENT_NOT_PENDING',

  // --- Order cancel (A-5, 2026-10-05) ---------------------------------------
  /** The order holds a deposit, so whoever cancels must say how much of it goes back (0 = the shop keeps it). */
  ORDER_REFUND_AMOUNT_REQUIRED: 'ORDER_REFUND_AMOUNT_REQUIRED',
  /** More refunded than the deposit still held. */
  ORDER_REFUND_EXCEEDS_DEPOSIT: 'ORDER_REFUND_EXCEEDS_DEPOSIT',

  // --- Order edit (A-8, 2026-10-06) -----------------------------------------
  /** An edit would drop an order line a production request was raised for; take it off the request first. */
  ORDER_ITEM_IN_PRODUCTION: 'ORDER_ITEM_IN_PRODUCTION',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
