allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@parcel/watcher': false
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@firebase/util'
  - '@google/genai'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
  - protobufjs
  - unrs-resolver
